Updated dockerfile and jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,32 +1,76 @@
 pipeline{
-    agent {label 'Frontend'}
+    agent any
     environment{
-        APP_SERVER = "172.31.41.100"
-        DEPLOY_DIR = "/var/www/html/"
+        IMAGE_NAME = 'dokesamruddhi/frontend-app'
+        IMAGE_TAG = "${BUILD_NUMBER}"
+        APP_SERVER = "13.127.65.225"
     }
     stages{
-        stage('Pre Build Actions'){
+        stage('Checkout'){
             steps{
-                sh 'npm install'
+                git branch: 'main', 
+                url: 'https://github.com/SamruddhiDoke/Jenkins-webapp.git'
             }
         }
-        stage('Build'){
+        stage('Build Docker Image'){
             steps{
-               sh 'npm run build'
+                sh '''
+                    docker build -f docker/dockerfile -t ${IMAGE_NAME}:${IMAGE_TAG} .
+                '''
             }
         }
-        stage('Post Build Actions'){
+        stage('Docker Login'){
             steps{
-                 sh """
-                    echo 'Cleaning old files on app server'
-                    ssh jenkins@${APP_SERVER} 'rm -rf ${DEPLOY_DIR}*'
-                    echo 'Copying frontend build'
-                    scp -r dist/. jenkins@${APP_SERVER}:${DEPLOY_DIR}
-                    echo 'Restarting nginx server'
-                    ssh jenkins@${APP_SERVER} 'sudo systemctl restart nginx'
-                    echo 'Deployment completed successfully'
-                 """
+                withCredentials(
+                    [usernamePassword(
+                        credentialsId: 'DockerCred', 
+                        usernameVariable: 'DOCKER_USER', 
+                        passwordVariable: 'DOCKER_PASS'
+                        )]) 
+                        {
+                    sh '''
+                        echo $DOCKER_PASS | docker login \ 
+                        -u $DOCKER_USER \
+                        --password-stdin
+                    '''
+                }
             }
         }
+        stage('Push Docker Image'){
+            steps{
+                sh '''
+                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
+                    docker tag \
+                    ${IMAGE_NAME}:${IMAGE_TAG} \
+                    ${IMAGE_NAME}:latest
+                    docker push ${IMAGE_NAME}:latest
+                '''
+            }
+        }
+        stage('Deploy to Server'){
+            steps{
+                sh '''
+                   ssh ubuntu@${APP_SERVER} "
+                   docker pull $IMAGE_NAME:latest
+                   docker stop frontend || true
+                   docker rm frontend || true
+                   docker run -d \
+                   --name frontend \
+                   -p 80:80 \
+                   $IMAGE_NAME:latest    
+                   "           
+                '''
+            }
+        }
+
+    
+}
+post{
+    success{
+        echo "Build and Deployment Successful"
     }
+    failure{
+        echo "Build or Deployment Failed"
+    }
+}
 }
